### ISSUE TITLE
Microsoft Computer Vision API key found in source

### ISSUE THREAD

**Issue by johnbindel** [glide143/inSight#1]
https://github.com/glide143/inSight/blob/3208415d06ebfb8da193cca67d832b687993e002/app/src/main/java/com/example/melchy/insight/OcrClass.java

Since the key is checked into public github, _anyone can see/use it_. Consider taking the following steps to remedy this:
1. get a new API key
2. retire usage of key
3. do this with config that is not-version controlled- don't check into GitHub

**Comment by glide143** [comment]
opps!, Didn't see that thanks for noticing it. Thank you 👍
